- name: "wolt: Create root directory to clone projects"
  file:
    state: directory
    path: ~/wolt

- name: "wolt: Checkout repos"
  ansible.builtin.command: "mr checkout"
  args:
    chdir: ~/wolt
  register: mr_checkout
- debug: var=mr_checkout.stdout
