- name: "poetry: Remove dir recommended by the docs"
  file:
    path: "~/.poetry"
    state: absent

# poetry is installed with mise

# https://python-poetry.org/docs/#enable-tab-completion-for-bash-fish-or-zsh
- name: "poetry: Bash completion"
  shell: "poetry completions bash > {{ ansible_env.BASH_COMPLETION_USER_DIR }}/completions/poetry.bash-completion"
  args:
    creates: "{{ ansible_env.BASH_COMPLETION_USER_DIR }}/completions/poetry.bash-completion"
