- name: Import Darwin-specific tasks
  ansible.builtin.import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- name: Import Debian-specific tasks
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install rustup
  ansible.builtin.shell: |
    set -o pipefail
    curl https://sh.rustup.rs -sSf | sh -s -- --no-modify-path  -y --default-toolchain nightly -v
  args:
    creates: ~/.cargo/env
  changed_when: false

# To avoid "error: no default toolchain configured" on cargo install
- name: Rustup install stable toolchain
  ansible.builtin.command: "~/.cargo/bin/rustup install stable"
  changed_when: false

- name: Rustup select stable toolchain
  ansible.builtin.command: "~/.cargo/bin/rustup default stable"
  changed_when: false

- name: Rustup install/update toolchains
  ansible.builtin.command: "~/.cargo/bin/rustup toolchain add {{ item }}"
  with_items:
    - stable
    - nightly
  when: "'rust_update_toolchain' | run_only_after"
  changed_when: false

- name: Install Rust utils (binaries)
  ansible.builtin.command: "~/.cargo/bin/cargo +nightly install {{ item.pkg }}"
  with_items: "{{ rust_binaries }}"
  changed_when: false
  # when: "'rust_install_binaries' | run_only_after"

- name: Install Rust utils from Git
  ansible.builtin.command: "~/.cargo/bin/cargo install --force --git {{ item.git }}"
  when: (rust_git_repos or False) and ('rust_install_from_git' | run_only_after)
  with_items:
    - "{{ rust_git_repos }}"
  changed_when: false

- name: Update installed binaries
  ansible.builtin.command: "~/.cargo/bin/cargo +nightly install-update -a"
  when: "'rust_update_binaries' | run_only_after"
  changed_when: false

- name: Install components
  ansible.builtin.command: "~/.cargo/bin/rustup component add {{ item }}"
  when: (rust_components or False) and ('rust_install_components' | run_only_after)
  with_items:
    - "{{ rust_components }}"
  tags: rust-components
  changed_when: false

- name: Link .ripgreprc file
  ansible.builtin.file:
    src: "{{ role_path }}/files/.ripgreprc.link"
    dest: "{{ dotfiles_user_home }}/.ripgreprc"
    state: link
    follow: false
