- name: Import secret ssh key file
  include_vars: "keys.yml"

- name: Write the content to a respective files.
  copy:
    content: "{{ item.value }}"
    dest: "~/demo/{{ item.key }}_gen"
    mode: 0600
    state: directory
  with_dict: "{{ key_files }}"

- name: Copy the ssh config file to the correct folder.
  copy:
    src: "../vars/config"
    dest: "~/demo/config"
