# http://www.hammerspoon.org/
- name: Install Hammerspoon with Homebrew
  homebrew_cask: name=hammerspoon state=present
  when: ansible_os_family == "Darwin"

- name: "Create ~/.hammerspoon"
  file:
    state: directory
    path: ~/.hammerspoon

- name: Link ~/.hammerspoon/init.lua
  file:
    src: "{{ role_path }}/files/init.lua"
    dest: "~/.hammerspoon/init.lua"
    state: link

- name: "Create ~/.hammerspoon/Spoons"
  file:
    state: directory
    path: ~/.hammerspoon/Spoons

- name: Clone Lunette
  git:
    repo: https://github.com/scottwhudson/Lunette
    dest: "~/.hammerspoon/Lunette"

- name: "Link Lunette spoon"
  file:
    src: ~/.hammerspoon/Lunette/Source/Lunette.spoon
    dest: ~/.hammerspoon/Spoons/Lunette.spoon
    state: link
