# https://github.com/wting/autojump

# https://github.com/wting/autojump#os-x
- name: "autojump: Install with Homebrew"
  community.general.homebrew:
    name: autojump
    state: present
  when: ansible_os_family == "Darwin"

- name: "autojump: Add content to ~/.bash_profile"
  blockinfile:
    path: ~/.bash_profile
    marker: "# ==================== {mark} https://github.com/junegunn/fzf/wiki/Examples#autojump"
    block: |
      # shellcheck source=/dev/null
      [ -f "$HOMEBREW_PREFIX"/etc/profile.d/autojump.sh ] && source "$HOMEBREW_PREFIX"/etc/profile.d/autojump.sh

      # https://github.com/junegunn/fzf/wiki/Examples#autojump
      # Using eza instead of exa
      j() {
          local preview_cmd="ls {2..}"
          if command -v eza &> /dev/null; then
              preview_cmd="eza -l {2}"
          fi

          if [[ $# -eq 0 ]]; then
              cd "$(autojump -s | sort -k1gr | awk -F : '$1 ~ /[0-9]/ && $2 ~ /^\s*\// {print $1 $2}' | fzf --height 40% --reverse --inline-info --preview "$preview_cmd" --preview-window down:50% | cut -d$'\t' -f2- | sed 's/^\s*//')" || return
          else
              cd "$(autojump "$@")" || return
          fi
      }

      # https://github.com/wting/autojump#known-issues
      # https://superuser.com/questions/1158739/prompt-command-to-reload-from-bash-history
      export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND ;} history -a; history -r"
