# https://github.com/wting/autojump

# https://github.com/wting/autojump#os-x
- name: "autojump: Install with Homebrew"
  homebrew: name=autojump state=present
  when: ansible_os_family == "Darwin"

- name: "autojump: Add content to .bashrc"
  blockinfile:
    path: ~/.bashrc
    marker: "# ==================== {mark} https://github.com/junegunn/fzf/wiki/Examples#autojump"
    block: |
      [ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
      j() {
          if [[ "$#" -ne 0 ]]; then
              cd "$(autojump "$@")" || return
              return
          fi
          cd "$(autojump -s | sort -k1gr | awk '$1 ~ /[0-9]:/ && $2 ~ /^\// { for (i=2; i<=NF; i++) { print $(i) } }' |  fzf --height 40% --reverse --inline-info)" || exit
      }

      # https://github.com/wting/autojump#known-issues
      export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND ;} history -a"
