# https://stackoverflow.com/questions/15330775/what-does-gdate-mean-in-this-shell-script
- name: "Link GNU gdate if not found"
  shell: "command -v gdate || sudo ln -s $(which date) /bin/gdate"

- name: "Copy private local variables"
  copy:
    src: ~/.config/dotfiles/local.env
    dest: ~/.config/dotfiles/local.env
    mode: "0600"
    force: yes

- name: "Copy .bash_profile file"
  copy:
    src: "{{ role_path }}/files/.bash_profile.sh"
    dest: ~/.bash_profile
    mode: "0600"
    force: yes
    follow: false

- name: "Copy .bashrc file"
  copy:
    src: "{{ role_path }}/files/.bashrc.sh"
    dest: ~/.bashrc
    mode: "0600"
    force: yes
    follow: false

- name: "Copy .inputrc file"
  copy:
    src: "{{ role_path }}/files/.inputrc"
    dest: ~/.inputrc
    mode: "0600"
    force: yes
    follow: false
