- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  environment:
    PYENV_ROOT: "{{ pyenv_root }}"
  roles:
    - {role: git, tags: [vcs]}
    - {role: package_manager, tags: [system]}
    - {role: zsh, tags: [system, bootstrap]}
    - {role: docker, tags: [system, fail]}
    - {role: vim, tags: [tool, dev]}
    - {role: python_pyenv, tags: [dev]}
    - {role: hub, tags: [vcs]}
    - {role: zsh-autoenv, tags: [system]}
    - {role: rg, tags: [tool]}
    - {role: exa, tags: [tool]}
    - {role: ccat, tags: [tool]}
    - {role: tmux, tags: [tool]}
    - {role: fzf, tags: [tool]}
    - {role: gnome_do, tags: [tool]}
    - {role: defaultbrowser, tags: [tool]}
    - {role: osx, when: ansible_os_family == "Darwin"}
    - {role: andreoliwa, tags: [personal]}
    - {role: eatfirst, tags: [personal]}
