- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  environment:
    PYENV_ROOT: "{{ pyenv_root }}"
  roles:
    - git
    - package_manager
    - {role: zsh, tags: ['bootstrap']}
    - {role: ~/.ansible/roles/mongrelion.docker,
      become: true,
      become_user: root,
      tags: ['bootstrap']}
    - ~/.ansible/roles/andrewrothstein.docker-compose
    - vim
    - python_pyenv
    - python_personal
    - python_eatfirst
    - hub
    - zsh-autoenv
    - rg
    - exa
    - ccat
    - tmux
    - fzf
    - gnome_do
    - {role: osx, when: ansible_os_family == "Darwin"}
    - eatfirst
