- name: Set up local development environment
  hosts: local
  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - { role: ansible, tags: ["ansible"] }
    - { role: bash, tags: ["bash"] }
    - { role: git, tags: ["git"] }
    - { role: package_manager, tags: ["package_manager", "bootstrap"] }
    - { role: vagrant, tags: ["vagrant"], when: ansible_os_family == "Darwin" }
    - { role: python_pyenv, tags: ["python"] }
    - { role: node, tags: ["node"] }
    - { role: hub, tags: ["hub"] }
    - { role: vim, tags: ["vim"] }
    - { role: rust, tags: ["rust"] }
    - { role: bat, tags: ["bat"] }
    - { role: tmux, tags: ["tmux"] }
    - { role: fzf, tags: ["fzf"] }
    - { role: macos, tags: ["macos"], when: ansible_os_family == "Darwin" }
    - {
        role: gantsign.visual-studio-code,
        tags: ["vscode"],
        when: ansible_os_family != "Darwin",
      }
    - { role: gnome_do, tags: ["gnome_do"] }
    - { role: browser, tags: ["browser"] }
    - { role: gitup, tags: ["gitup"] }
    - { role: andreoliwa, tags: ["andreoliwa", "personal"] }
    - { role: eatfirst, tags: ["eatfirst", "personal"] }
    - { role: docker, tags: ["docker"] }
    - { role: postgres, tags: ["postgres", "pg", "sql"] }
    - { role: redmine, tags: ["redmine"] }
    - { role: mayan-edms, tags: ["mayan"] }
    - { role: tt-rss, tags: ["tt-rss", "rss"] }
