- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  environment:
    PYENV_ROOT: "{{ pyenv_root }}"
  roles:
    - {role: git, tags: vcs}
    - package_manager
    - {role: zsh, tags: shell, bootstrap}
    - {role: docker, tags: bootstrap}
    - vim
    - python_pyenv
    - {role: hub, tags: vcs}
    - {role: zsh-autoenv, tags: shell}
    - {role: rg, tags: tool}
    - {role: exa, tags: tool}
    - {role: ccat, tags: tool}
    - {role: tmux, tags: tool}
    - {role: fzf, tags: tool}
    - {role: gnome_do, tags: tool}
    - {role: osx, when: ansible_os_family == "Darwin"}
    - {role: andreoliwa, tags: personal}
    - {role: eatfirst, tags: personal}
