- name: Collecting Facts
  hosts: local
  gather_facts: yes

- name: Set up local development environment
  hosts: local
  environment:
    PYENV_ROOT: "{{ pyenv_root }}"
  roles:
    - {role: git, tags: [git, vcs]}
    - {role: package_manager, tags: [os, system]}
    - {role: xonsh, tags: [xonsh, system]}
    - {role: docker, tags: [docker, system, fail]}
    - {role: vim, tags: [vim, tool, dev]}
    - {role: python_pyenv, tags: [python, dev]}
    - {role: rust, tags: [rust]}
    - {role: node, tags: [node, dev]}
    - {role: hub, tags: [hub, vcs]}
    - {role: ccat, tags: [ccat, tool]}
    - {role: tmux, tags: [tmux, tool]}
    - {role: fzf, tags: [fzf, tool]}
    - {role: gnome_do, tags: [gnome_do, tool]}
    - {role: defaultbrowser, tags: [tool]}
    - {role: osx, tags: [os, system], when: ansible_os_family == "Darwin"}
    - {role: andreoliwa, tags: [andreoliwa, personal]}
    - {role: eatfirst, tags: [eatfirst, personal]}
    - {role: gitup, tags: [gitup, vcs]}
