- name: Set up the Hetzner instance
  hosts: rlyeh
  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - { role: git, tags: ["git"] }
    - { role: security, tags: ["security", "ssh", "gpg"] }
    - { role: bash, tags: ["bash"] }
    - { role: remote-server, tags: ["remote", "hetzner"] }
    - { role: invoke, tags: ["invoke"] }
