- name: Set up the DigitalOcean instance
  hosts: ocean
  roles:
    # Tag each role so that we can select individual roles to run with ansible-playbook --tags
    - { role: git, tags: ["git"] }
    - { role: bash, tags: ["bash"] }
    - { role: remote-server, tags: ["remote", "ocean"] }
