requires = ["brew_bundle"]
tier = "FINAL"

[names]
"409203825"  = "Numbers"
"973134470"  = "Be Focused - Focus Timer"
"1153157709" = "Speedtest by Ookla"
"1291898086" = "Toggl Track"
"526298438"  = "Lightshot Screenshot"
"585829637"  = "Todoist"

[packages.common]
install = [
    409203825,
    973134470,
]
remove = [
    1153157709,
    1291898086,
    526298438,
    585829637,
]

[packages.company]
install = []
remove = []

[packages.personal]
install = []
remove = []
