- name: "openssl: Add env vars to shell script"
  shell: "brew info openssl | grep ' export ' | awk '{$1=$1};1' > ~/.config/dotfiles/openssl.env"
  when: ansible_os_family == "Darwin"

- name: "openssl: Export vars on .bashrc"
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: "/.config/dotfiles/openssl.env"
    line: 'test -f "$HOME"/.config/dotfiles/openssl.env && source "$HOME"/.config/dotfiles/openssl.env'
    insertafter: "test -f"
  when: ansible_os_family == "Darwin"
