- name: "direnv: Uninstall with Homebrew"
  homebrew: name=direnv state=absent
  when: ansible_os_family == "Darwin"

- name: "direnv: Uninstall with apt"
  apt: name=direnv state=absent
  become: true
  when: ansible_os_family == "Debian"

- name: "direnv: Uninstall with apt"
  apt: name=direnv state=absent
  become: true
  when: ansible_os_family == "OSMC"

- name: "direnv: Add as asdf plugin"
  command: "asdf plugin-add direnv"
  register: this_task
  args:
    creates: ~/.asdf/plugins/direnv

- name: "direnv: Install latest with asdf"
  command: "asdf install direnv latest"
  register: this_task
  changed_when: "'is already installed' not in this_task.stdout"

- name: "direnv: Set global with asdf"
  command: "asdf global direnv latest"

- name: "direnv: Add content to .bash_profile"
  blockinfile:
    path: ~/.bash_profile
    marker: "# ==================== {mark} https://github.com/direnv/direnv"
    block: |
      # https://github.com/asdf-community/asdf-direnv#setup
      eval "$(asdf exec direnv hook bash)"
      direnv() { asdf exec direnv "$@"; }
