- name: "direnv: Install with Homebrew"
  homebrew: name=direnv state=latest
  when: ansible_os_family == "Darwin"

- name: "direnv: Install with apt"
  apt: name=direnv state=latest
  become: true
  when: ansible_os_family in ("Debian", "OSMC")

- name: "direnv: Add content to .bashrc"
  blockinfile:
    path: ~/.bashrc
    marker: "# ==================== {mark} https://github.com/direnv/direnv"
    block: |
      # https://direnv.net/docs/hook.html#bash
      eval "$(direnv hook bash)"
