#!/usr/bin/env bash

# Let Homebrew modify the PATH before everything else, so tools like pyenv can be first in the PATH.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Suggestions made by pyenv init:
# WARNING: `pyenv init -` no longer sets PATH.
# Run `pyenv init` to see the necessary changes to make to your configuration.
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
command -v pyenv >/dev/null && eval "$(pyenv init -)"

# shellcheck disable=SC1091
test -f "$HOME/.bashrc" && source "${HOME}/.bashrc"
# shellcheck disable=SC1091
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# https://docs.brew.sh/Shell-Completion
if type brew &>/dev/null; then
    HOMEBREW_PREFIX="$(brew --prefix)"
    if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
        # shellcheck disable=SC1091
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
    else
        for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
            # shellcheck source=/dev/null
            [[ -r "$COMPLETION" ]] && source "$COMPLETION"
        done
    fi
fi

# Where should I install my own local completions?
# https://github.com/scop/bash-completion/blob/master/README.md#faq
if [[ -d "$BASH_COMPLETION_USER_DIR/completions" ]]; then
    for COMPLETION in "$BASH_COMPLETION_USER_DIR/completions/"*; do
        # shellcheck source=/dev/null
        source "$COMPLETION"
    done
fi

# https://github.com/tiangolo/typer installs completion files in this directory
if [[ -d "$HOME/.bash_completions/" ]]; then
    for COMPLETION in "$HOME/.bash_completions/"*; do
        # shellcheck source=/dev/null
        [[ -r "$COMPLETION" ]] && source "$COMPLETION"
    done
fi

# Added by OrbStack: command-line tools and integration
# shellcheck source=/dev/null
source ~/.orbstack/shell/init.bash 2>/dev/null || :

# https://discussions.apple.com/thread/251000125
ulimit -n 1024

# ==================== BEGIN https://github.com/junegunn/fzf/wiki/Examples#autojump
# shellcheck source=/dev/null
[ -f "$HOMEBREW_PREFIX"/etc/profile.d/autojump.sh ] && source "$HOMEBREW_PREFIX"/etc/profile.d/autojump.sh

# https://github.com/junegunn/fzf/wiki/Examples#autojump
# Using eza instead of exa
j() {
    local preview_cmd="ls {2..}"
    if command -v eza &> /dev/null; then
        preview_cmd="eza -l {2}"
    fi

    if [[ $# -eq 0 ]]; then
        cd "$(autojump -s | sort -k1gr | awk -F : '$1 ~ /[0-9]/ && $2 ~ /^\s*\// {print $1 $2}' | fzf --height 40% --reverse --inline-info --preview "$preview_cmd" --preview-window down:50% | cut -d$'\t' -f2- | sed 's/^\s*//')" || return
    else
        cd "$(autojump "$@")" || return
    fi
}

# https://github.com/wting/autojump#known-issues
# https://superuser.com/questions/1158739/prompt-command-to-reload-from-bash-history
export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND ;} history -a; history -r"
# ==================== END https://github.com/junegunn/fzf/wiki/Examples#autojump
