rpi_apt_packages:
  - lsb-release
  - htop
  - lsof
  - strace
  - tmux
  - cron
  - gddrescue
  - pv
  - testdisk
  - docker-ce
  - docker-compose
  - zerotier-one # https://www.zerotier.com/download.shtml
