galaxy_info:
  author: Suzuki Shunsuke
  description: Install pyenv-virtualenv
  license: MIT
  min_ansible_version: 2.2
  github_branch: master
  platforms:
  - name: GenericLinux
  - name: MacOSX

  galaxy_tags:
  - python
  - pyenv
  - pyenv-virtualenv

dependencies: []
