# https://github.com/nosarthur/gita
- name: "gita: Install with pipx"
  command: "pipx install gita"
  register: result
  failed_when:
    - result.rc > 0
    - "'Not installing to existing directory' not in result.stderr"
    - "'already seems to be installed' not in result.stdout"

- name: "gita: Get brew prefix"
  command: "brew --prefix"
  register: brew_prefix

- name: "gita: Tab completion"
  get_url:
    url: "https://raw.githubusercontent.com/nosarthur/gita/master/.gita-completion.bash"
    dest: "{{ brew_prefix.stdout }}/etc/bash_completion.d/gita.bash-completion"

- name: "gita: Add dotfiles"
  command: "gita add {{ dotfiles_home }}"

- name: "gita: Add dotfiles to the 'personal' group"
  command: "gita group add -n personal dotfiles"
