- import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"
- import_tasks: debian.yml
  when: ansible_os_family in ("Debian", "OSMC")
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: gitconfig.yml
  when:
    - ansible_distribution not in ("Amazon", "OSMC")
    - ansible_system_vendor is not defined or ansible_system_vendor != "DigitalOcean"

- name: "gita: Import tasks"
  debug: msg="I want to use --start-at-task here, but 'name' is ignored on 'import_tasks'"
- import_tasks: gita.yml
  when:
    - ansible_distribution not in ("Amazon", "OSMC")
    - ansible_system_vendor is not defined or ansible_system_vendor != "DigitalOcean"
