version: "3.5"

services:
  app:
    container_name: node-red
    build: .
    ports:
      - "1880:1880"
    volumes:
      - ./var/data:/data
      - ~/Downloads:/mnt/downloads
      - ~/Dropbox/Inbox:/mnt/inbox
      - ~/Personal/transmission-openvpn/completed:/mnt/completed
