# https://organize.readthedocs.io/en/latest/page/config.html#configuration
move_folders: &move
  - ~/OneDrive/Documents/Mayan_Staging/Deutsch
  - ~/OneDrive/Documents/Mayan_Staging/Portugues

slugify_folders: &slugify
  - ~/Documents
  - ~/Downloads/
  - ~/Desktop/
  - ~/Library/Mobile Documents/com~apple~QuickTimePlayerX/Documents
  - ~/OneDrive/

mobile_upload_folders: &mobile_upload
  - ~/OneDrive/Pictures/Camera Roll/
  - ~/OneDrive/Pictures/Download/
  # TODO chore: this doesn't work in version 2.0.3; try again when there will be a new version with fixes
  # - ~/OneDrive/Pictures/Facebook/
  - ~/OneDrive/Pictures/Screenshots/
  - ~/OneDrive/Pictures/Telegram/
  - ~/OneDrive/Pictures/WhatsApp Animated Gifs/
  - ~/OneDrive/Pictures/WhatsApp Images/
  - ~/OneDrive/Pictures/WhatsApp Video/
  # TODO chore: this doesn't work in version 2.0.3; try again when there will be a new version with fixes
  # - ~/OneDrive/Pictures/Samsung Gallery/

rules:
  # Hack to call rename-slugify only once.
  # As of March 2020, the organize tool only finds *files* under directories...
  # it doesn't find directories, so I can't rename them
  # TODO chore: this doesn't work in version 2.0.3; try again when there will be a new version with fixes
  - locations:
      - ~/
    filters:
      - name:
          startswith: .bashrc
    actions:
      - shell: "fd -uu -0 -tf -i .DS_Store ~/Downloads ~/Desktop ~/OneDrive ~/Documents | xargs -0 rm -v"
      - shell: "fd -uu -0 -tf -i .nomedia ~/Downloads ~/Desktop ~/OneDrive ~/Documents | xargs -0 rm -v"
      - shell: "find -f ~/Downloads -f ~/Desktop -f ~/Documents ~/OneDrive -mindepth 1 -type d -empty -print -delete"
      # Use this to debug:
      # cd ~/Code/python-clib && poetry run
      - shell: "rename-slugify -x ~/OneDrive/Bluecoins -x ~/OneDrive/Musicas_LuisAndreoli -x ~/OneDrive/Movies/ -x ~/OneDrive/Documents/Nati_Wa/Finanças -x ~/Documents/Code/ -x ~/Documents/Notebook/ -x ~/OneDrive/Books/ -x ~/OneDrive/Backup/ -x ~/OneDrive/Apps/ -x ~/OneDrive/Code/ -x ~/OneDrive/Icon? -x '~/OneDrive/Pictures/Camera Roll/' -x '~/OneDrive/Pictures/Download/' -x '~/OneDrive/Pictures/Facebook/' -x '~/OneDrive/Pictures/Screenshots/' -x '~/OneDrive/Pictures/Telegram/' -x '~/OneDrive/Pictures/WhatsApp Animated Gifs/' -x '~/OneDrive/Pictures/WhatsApp Images/' -x '~/OneDrive/Pictures/WhatsApp Video/' -x '~/OneDrive/Pictures/Samsung Gallery/' -x ~/OneDrive/Documents/Nati_Wa/Site_Natalie --yes ~/Documents ~/Downloads/ ~/Desktop/ ~/Library/Mobile\\ Documents/com~apple~QuickTimePlayerX/Documents ~/OneDrive/"

  # This works, but it got stuck during scanning, maybe because of how organize scans directories.
  # fd/find were dismissed: https://github.com/tfeldmann/organize/issues/84
  # It seems that the "system_files" was removed in version 2.0: https://github.com/tfeldmann/organize/issues/166
  # TODO chore: this doesn't work in version 2.0.3; try again when there will be a new version with fixes
  # - locations: *slugify
  #   subfolders: true
  #   system_files: true
  #   filters:
  #     - name:
  #         startswith: .DS_Store
  #   actions:
  #     - trash

  # Receipts
  - locations: *move
    filters:
      - filecontent: "(?P<store>REWE|Kaufland|Lidl|Aldi|EDEKA|Rossmann|Penny|Budni|LPG Biomarkt|Nanu-Nana|Tiger Deutschland)"
    actions:
      # TODO chore: this doesn't work in version 2.0.3; try again when there will be a new version with fixes
      # See https://github.com/tfeldmann/organize/issues/168
      - move: "~/OneDrive/Documents/Mayan_Staging/Companies/{filecontent.store}/Receipt/"
  # Invoices
  - locations: *move
    filters:
      - filecontent: "(Rechnung)"
    actions:
      - move: "~/OneDrive/Documents/Mayan_Staging/Deutsch/Type_Invoice/"
  - locations: *move
    filters:
      - name:
          contains:
            - extrato
            - tesouro
            - btg
            - pactual
            - vsc11
            - ird11
          case_sensitive: false
    actions:
      - move: "~/OneDrive/Documents/Mayan_Staging/Cabinets/Investimentos/"
  - locations: *move
    filters:
      - name:
          startswith:
            - clear
            - monetus
            - rico
          case_sensitive: false
    actions:
      - move: "~/OneDrive/Documents/Mayan_Staging/Cabinets/Investimentos/"
  - locations: *move
    filters:
      - name:
          contains:
            - Umsatz
            - Ums_Mt
            - Camt52
          case_sensitive: false
    actions:
      - move: "~/OneDrive/Geld/Sparkasse/"
  - locations: *move
    filters:
      - name:
          contains:
            - riema
            - miami gardens
            - miami_gardens
            - live_tim
          case_sensitive: false
    actions:
      - move: "~/OneDrive/Geld/Contas_Alisson/"
  - locations: *move
    filters:
      - name:
          startswith:
            - gps_
            - progresso_
          case_sensitive: false
    actions:
      - move: "~/OneDrive/Geld/Juridica/"
  - locations:
      - *mobile_upload
      - *move
    subfolders: true
    filters:
      - name:
          contains:
            # WhatsApp
            - -WA
            - _wa_
            - whats_app
            - whatsapp
          case_sensitive: false
      - lastmodified:
          years: 1
          mode: newer
    actions:
      - move: "~/OneDrive/New_Chat/{lastmodified.strftime('%Y/%m')}/"
  - locations:
      - *mobile_upload
    subfolders: true
    filters:
      - name:
          startswith:
            # Telegram
            - "1_"
            - "2_"
            - "3_"
            - "4_"
            - "5_"
            - "22"
            - "23"
            - "42"
            - "70"
            - "71"
            - "80"
            - "81"
            # Facebook Messenger
            - Received
            # Facebook
            - fb_img_
          case_sensitive: false
      - lastmodified:
          years: 1
          mode: newer
    actions:
      - move: "~/OneDrive/New_Chat/{lastmodified.strftime('%Y/%m')}/"
  - locations:
      - *mobile_upload
    subfolders: true
    filters:
      - name:
          startswith:
            - Screenshot_
            - Temp_File_For_Share
          case_sensitive: false
      - lastmodified:
          years: 1
          mode: newer
    actions:
      - move: "~/OneDrive/New_Screenshots/{lastmodified.strftime('%Y/%m')}/"

  - locations:
      - *mobile_upload
    subfolders: true
    filters:
      - name:
          startswith:
            - P_
            - "20"
          case_sensitive: false
      - lastmodified:
          years: 1
          mode: newer
    actions:
      - move: "~/OneDrive/Pictures/Camera_New/{lastmodified.strftime('%Y/%m')}/"

  - locations:
      - path: ~/OneDrive/Pictures/Classify/
        ignore_errors: true
      - path: ~/OneDrive/Pictures/Organize/
        ignore_errors: true
    subfolders: true
    filters:
      - lastmodified:
          years: 1
          mode: newer
    actions:
      - move: "~/OneDrive/Pictures/New_Split/{lastmodified.strftime('%Y/%m')}/"

  # https://organize.readthedocs.io/en/latest/page/actions.html#id9
