# https://github.com/andreoliwa/conjuring-private
- name: "invoke-conjuring-private: Clone"
  git:
    repo: git@github.com:andreoliwa/conjuring-private.git
    dest: "{{ project_root }}/conjuring-private"
  ignore_errors: yes

- name: "invoke-conjuring-private: Default work tasks"
  blockinfile:
    path: ~/conjuring_work.py
    create: yes
    marker: "# ==================== {mark} https://github.com/andreoliwa/conjuring-private"
    block: |
      from conjuring_private.sennder import *
      from conjuring_private.wolt import *
      from conjuring_private.black_magic import *

- name: "invoke-conjuring-private: Default Todoist tasks"
  blockinfile:
    path: "{{ project_root }}/todoist/conjuring_todoist.py"
    create: yes
    marker: "# ==================== {mark} https://github.com/andreoliwa/conjuring-private"
    block: |
      from conjuring_private.todoist import *

# TODO: hack to install a Poetry package as editable until https://github.com/python-poetry/poetry-core/pull/182 is merged
- name: "invoke-conjuring-private: Rename pyproject.toml"
  command: "mv pyproject.toml _pyproject.toml"
  args:
    chdir: "{{ project_root }}/conjuring-private/"
  ignore_errors: yes
- name: "invoke-conjuring-private: Inject"
  command: "pipx inject -e invoke ."
  args:
    chdir: "{{ project_root }}/conjuring-private/"
- name: "invoke-conjuring-private: Restore pyproject.toml"
  shell: "mv _pyproject.toml pyproject.toml"
  args:
    chdir: "{{ project_root }}/conjuring-private/"
  ignore_errors: yes
