- import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

# https://github.com/nvm-sh/nvm
- name: Install nvm
  script: install_nvm.sh
  args:
    creates: "{{dotfiles_user_home}}/.nvm"
