- name: Uninstall node and npm with homebrew
  homebrew:
    name: node
    state: absent
  # Refusing to uninstall /usr/local/Cellar/node/18.8.0\nbecause it is required by bitwarden-cli
  ignore_errors: true

- name: "nodejs: Add as asdf plugin"
  command: "asdf plugin-add nodejs"
  args:
    creates: ~/.asdf/plugins/nodejs

- name: "nodejs: Install latest with asdf"
  command: "asdf install nodejs latest"
  register: result
  changed_when: "'is already installed' not in result.stdout"

- name: "nodejs: Set global with asdf"
  command: "asdf global nodejs latest"
