- name: Uninstall yarn with homebrew
  homebrew:
    name: yarn
    state: absent

- name: "yarn: Add as asdf plugin"
  command: "asdf plugin-add yarn"
  args:
    creates: ~/.asdf/plugins/yarn

# TODO installation is failing with:
# Resolving github.com (github.com)... 140.82.121.4
# Connecting to github.com (github.com)|140.82.121.4|:443... connected.
# HTTP request sent, awaiting response... 404 Not Found
# 2024-03-23 01:11:31 ERROR 404: Not Found.

# - name: "yarn: Install latest with asdf"
#   command: "asdf install yarn latest"
#   register: result
#   changed_when: "'is already installed' not in result.stdout"

# - name: "yarn: Set global with asdf"
#   command: "asdf global yarn latest"

# https://github.com/dsifford/yarn-completion
- name: "yarn: Bash completion"
  get_url:
    url: "https://raw.githubusercontent.com/dsifford/yarn-completion/master/yarn-completion.bash"
    dest: "{{ ansible_env.BASH_COMPLETION_USER_DIR }}/completions/yarn-completion.bash"
