- name: Make sure xonsh is installed
  homebrew: name=xonsh state=latest

- name: Add xonsh to /etc/shells
  lineinfile:
    line: /usr/local/bin/xonsh
    dest: /etc/shells
    state: present
  register: add_xonsh
  become: true
  become_method: sudo
  tags: [bootstrap]

- name: Change default shell to xonsh
  command: chsh -s /usr/local/bin/xonsh
  tags: [bootstrap]
  # Only run this if above task was changed
  when: add_xonsh.changed
