- name: "Install xonsh with apt (it's not the latest version)"
  apt: name=xonsh state=latest

- name: "Upgrade xonsh to the latest version with xpip"
  command: "xonsh --no-rc -c 'xpip install -U xonsh'"

- name: Change default shell to xonsh
  become: true
  command: chsh -s /usr/bin/xonsh
  tags: [bootstrap]

