- name: Install xonsh with Homebrew
  homebrew: name=xonsh state=latest
  when: ansible_os_family == "Darwin"

- name: Install xonsh with apt
  apt: name=git state=latest
  become: true
  when: ansible_os_family != "Darwin"

- name: "Update xonsh to the latest version with global pip3"
  pip:
    name: xonsh
    state: latest
    executable: pip3
  when: ansible_os_family != "Darwin"
