- name: "Install Xontribs (xpip install)"
  with_items: '{{ xontribs_install }}'
  command: "xonsh --no-rc -c 'xpip install -U {{ item }}'"
  when: ansible_os_family == "Darwin"

- name: "Install Xontribs (system Python 3)"
  with_items: '{{ xontribs_install }}'
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  when: ansible_os_family != "Darwin"

- name: "Remove ~/.xonsh_xontrib_load"
  file:
    state: absent
    path: "{{ dotfiles_user_home }}/.xonsh_xontrib_load"

- name: "Load Xontribs (using ~/.xonsh_xontrib_load)"
  with_items: '{{ xontribs_load }}'
  lineinfile:
    path: "{{ dotfiles_user_home }}/.xonsh_xontrib_load"
    state: present
    create: yes
    regexp: "{{ item }}"
    line: "xontrib load {{ item }}"
