- name: "Link docker.bash-completion"
  file:
    src: "/Applications/Docker.app/Contents/Resources/etc/docker.bash-completion"
    dest: "{{ mac_homebrew_prefix }}/etc/bash_completion.d/docker.bash-completion"
    state: link
    force: yes
    follow: false

- name: "Link docker-compose.bash-completion"
  file:
    src: "/Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion"
    dest: "{{ mac_homebrew_prefix }}/etc/bash_completion.d/docker-compose.bash-completion"
    state: link
    force: yes
    follow: false
