# Git repo URL
# The only required argument. Some examples:
#repo: "git@github.com:some_user/some_repo.git"
#repo: "https://github.com/some_user/some_repo.git"
#repo: "git@bitbucket.org:some_user/some_repo.git"

# Directory to clone the repo.
# Default: repo name.
dir: "{{ repo.split('/')[-1].split('.')[0] }}"

# Root directory for the repo.
# Default: project root defined in group_vars/local
root: "{{ project_root }}"

# By default, the virtualenv name is the same as the directory name
env: "{{ dir }}"

# Update the git repo
update: no

# Python version for the pyenv virtualenv
# If the version is not informed, a virtualenv will not be created
python_version: ""

# Versions set by the "pyenv local" command (after the repo's virtualenv)
local: "{{ env }}"

# Directory containing .link files that will become symbolic links in the project root
symlink_dir: ""

# User name and email for the repo. Ignored when empty (will use the global git config)
user_name: ""
user_email: ""

# gita group for the project
gita_group: ""
